### ISSUE TITLE
Best use case and examples for functions in complex plane

### ISSUE THREAD

**Issue by heltonmc** [stevengj/FastChebInterp.jl#11]
Thank you for this package! It has been very helpful over at Bessels.jl

Is the best way to use this package to approximate functions in the complex plane is by setting it up as a 2D problem?

```julia
g(x) = sin(x[1] + im*x[2])
lb, ub = [1,3], [2,4]
x = chebpoints((10, 20), lb, ub)
c = chebinterp(g.(x), lb, ub)

julia> g([1.2, 3.4])
13.979408806017995 + 5.422815472463402im

julia> c([1.2, 3.4])
13.979408806018007 + 5.422815472463357im
```

Or is there a better more recommended approach to do this ?

-Michael

**Comment by stevengj** [comment]
Yes, I think so.

**Comment by heltonmc** [comment]
Perfect - Thank you!
