### ISSUE TITLE
Smolyak methods

### ISSUE THREAD

**Issue by marcobonici** [stevengj/FastChebInterp.jl#13]
Due to the curse of dimensionality, the number of coefficients that we need to evaluate in higher dimension grows rapidly.
A possible approach to reduce this problem is represented by [Smolyak grids](https://bfi.uchicago.edu/wp-content/uploads/Judd-Maliar-Valero-1.pdf).

I wonder whether it would be possible to add the Smolyak grid methods to this package.
If you are interested, I would be willing to help on this direction.
Cheers,
Marco Bonici

**Comment by stevengj** [comment]
I think that Smolyak interpolation would best be left to another package, and in fact there actually is a Smolyak package https://github.com/RJDennis/SmolyakApprox.jl

Of course, you are welcome to re-use any functionality in FastChebInterp if it is helpful in a Smolyak package, simply by depending on this package.  And if there are any changes/additions to the FastChebInterp API that would make it easier to build functionality like Smolyak grids on top of it, I would be open to suggestions.

(That being said, I have grown somewhat more skeptical of Smolyak interpolation over the years.  IIRC they work best when the function is mostly separable along the dimensions, whereas if there are lots of non-negligible mixed derivatives then the curse of dimensionality returns.)
